name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - name: Setup timezone
      #   uses: zcong1993/setup-timezone@master
      #   with:
      #     timezone: Australia/Melbourne

      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Build
        run: |
          bun install
          bun run build

      - name: Run legacy iCal tests
        run: bun test

      - name: Run Jest test suite
        run: bun run test
